spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: user
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


#  mail:
#    host: smtp.example.com
#    port: 587
#    username: setusername
#    password: setpassword
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true